'use strict';
const copy = {
 en:{languageLabel:'Language',eyebrow:'MENSTRUAL HEALTH, IN PLAIN LANGUAGE',heading:'Your period.\nYour questions.',intro:'Find straightforward answers about periods, products, and when to get help.',notice:'Draft for review. Medical content and Spanish translations have not yet been professionally reviewed. General education only; this FAQ cannot diagnose you.',searchLabel:'What would you like to know?',placeholder:'Try “tampon”, “cramps”, or “bleeding”',clear:'Clear',privacy:'Search stays in this browser. No account, cookies, analytics, or saved questions. Your hosting provider may record page visits.',emptyTitle:'No matching answer yet',emptyText:'Try a shorter search or another topic. We only show the answers in this FAQ. For personal symptoms, contact a clinician.',reset:'Show all questions',careEyebrow:'WHEN TO GET HELP',careTitle:'You deserve care.',careText:'Seek emergency care if you change pads or tampons every hour for more than 2 hours and also have dizziness, chest pain, or shortness of breath.',careAction:'For a medical emergency in the U.S., call 911. Elsewhere, use your local emergency number.',careSource:'Read ACOG guidance ↗',routine:'For heavy bleeding or pain that disrupts your day, contact a clinician, school nurse, or local health clinic.',findCare:'Find a U.S. health center ↗',aboutTitle:'Where the answers come from',aboutText:'Summaries link to FDA, CDC, ACOG, MedlinePlus, Planned Parenthood, NHS, and Office on Women’s Health resources. These organizations have not endorsed this project. Sources were checked October 1 and 4, 2026; this is not a clinical review.',footerText:'Period education · English & Español',pending:'Awaiting professional review',source:'Source',checked:'Source check: October 1, 2026',topics:'Topics',results:n=>`${n} ${n===1?'question':'questions'}`,categories:{all:'All questions',basics:'Period basics',products:'Products & hygiene',comfort:'Cramps & comfort',care:'When to get care'}},
 es:{languageLabel:'Idioma',eyebrow:'SALUD MENSTRUAL, EN PALABRAS SENCILLAS',heading:'Tu menstruación.\nTus preguntas.',intro:'Encuentra respuestas claras sobre la menstruación, los productos y cuándo buscar ayuda.',notice:'Borrador para revisión. El contenido médico y las traducciones al español aún no han sido revisados por profesionales. Solo ofrece educación general; no puede diagnosticarte.',searchLabel:'¿Qué te gustaría saber?',placeholder:'Prueba “tampón”, “cólicos” o “sangrado”',clear:'Borrar',privacy:'La búsqueda se queda en este navegador. Sin cuenta, cookies, análisis de uso ni preguntas guardadas. El proveedor de alojamiento puede registrar visitas.',emptyTitle:'Todavía no hay una respuesta coincidente',emptyText:'Prueba una búsqueda más corta u otro tema. Solo mostramos respuestas de esta guía. Para síntomas personales, consulta a un profesional de salud.',reset:'Mostrar todas las preguntas',careEyebrow:'CUÁNDO BUSCAR AYUDA',careTitle:'Mereces atención.',careText:'Busca atención de emergencia si cambias toallas o tampones cada hora durante más de 2 horas y además tienes mareos, dolor de pecho o falta de aire.',careAction:'Para una emergencia médica en EE. UU., llama al 911. En otros países, usa el número local de emergencias.',careSource:'Leer la guía de ACOG ↗',routine:'Si el sangrado abundante o el dolor afectan tu día, consulta a un profesional, personal de enfermería escolar o una clínica local.',findCare:'Buscar un centro de salud en EE. UU. ↗',aboutTitle:'De dónde vienen las respuestas',aboutText:'Los resúmenes enlazan a recursos de FDA, CDC, ACOG, MedlinePlus, Planned Parenthood, NHS y Office on Women’s Health. Estas organizaciones no han respaldado este proyecto. Las fuentes se comprobaron el 1 y el 4 de octubre de 2026; no es una revisión clínica.',footerText:'Educación menstrual · English & Español',pending:'Pendiente de revisión profesional',source:'Fuente',checked:'Comprobación de fuente: 1 de octubre de 2026',topics:'Temas',results:n=>`${n} ${n===1?'pregunta':'preguntas'}`,categories:{all:'Todas',basics:'Conceptos básicos',products:'Productos e higiene',comfort:'Cólicos y bienestar',care:'Cuándo buscar atención'}}
};
const $=id=>document.getElementById(id);
let lang='en',category='all';
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function make(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function link(text,url){const a=make('a',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function render(){const c=copy[lang],terms=normalize($('search').value).trim().split(/\s+/).filter(Boolean);
 const items=window.FAQ_DATA.items.filter(item=>(category==='all'||item.category===category)&&terms.every(term=>normalize([item[lang].q,item[lang].a,item.keywords[lang],c.categories[item.category]].join(' ')).includes(term)));
 $('count').textContent=c.results(items.length);$('empty').hidden=items.length!==0;$('results').replaceChildren();
 for(const item of items){const d=make('details');d.id=item.id;d.append(make('summary',item[lang].q),make('p',item[lang].a));const meta=make('div',undefined,'answer-meta');const source=window.FAQ_DATA.sources[item.source];meta.append(link(`${c.source}: ${source.name} ↗`,source.url),make('span',c.pending,'badge'));d.append(meta,make('p',item.sourceChecked ? (lang==='en' ? 'Source check: '+item.sourceChecked : 'Comprobación de fuente: '+item.sourceChecked) : c.checked,'count'));$('results').append(d);}
 for(const button of $('filters').children)button.setAttribute('aria-pressed',String(button.dataset.category===category));
}
function setLanguage(){lang=$('language').value;document.documentElement.lang=lang;document.title=lang==='en'?'Period questions · Return Gifts':'Preguntas sobre la menstruación · Return Gifts';const c=copy[lang];
 for(const [key,value] of Object.entries(c)){const el=$(key);if(el&&typeof value==='string')el.textContent=value;}
 $('heading').style.whiteSpace='pre-line';$('search').placeholder=c.placeholder;$('language').setAttribute('aria-label',c.languageLabel);$('filters').setAttribute('aria-label',c.topics);document.querySelector('.skip').textContent=lang==='en'?'Skip to questions':'Ir a las preguntas';$('filters').replaceChildren();
 for(const [key,label] of Object.entries(c.categories)){const b=make('button',label);b.type='button';b.dataset.category=key;b.addEventListener('click',()=>{category=key;render();});$('filters').append(b);}
 $('sources').replaceChildren(...Object.values(window.FAQ_DATA.sources).map(s=>link(s.name+' ↗',s.url)));render();
}
$('language').addEventListener('change',setLanguage);$('search').addEventListener('input',render);$('clear').addEventListener('click',()=>{$('search').value='';render();$('search').focus();});$('reset').addEventListener('click',()=>{category='all';$('search').value='';render();$('search').focus();});setLanguage();
